### ISSUE TITLE
Java Test case failed.

### ISSUE THREAD

**Issue by hemanth22** [hemanth22/GroovyLearning#2]
Java Test case failed with below error.

org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/home/travis/build/hemanth22/GroovyLearning/AddTests.groovy: 6: unexpected token: ; @ line 6, column 24.
   		def account = new Add;
                          ^
1 error

**Comment by hemanth22** [comment]
I am working on it.

**Comment by hemanth22** [comment]
Identified the Issue.

Javap show's gives some hint to re-write Groovy test.

0.85s$ docker run --rm -v"$PWD":/usr/src/myapp -w /usr/src/myapp java:7 javap Add.class
Compiled from "Add.java"
class Add {
  Add();
  public static void main(java.lang.String[]);
  static int addition(int, int);
}

**Comment by hemanth22** [comment]
Test fix applied.
Let's see what will be output.

**Comment by hemanth22** [comment]
Now you can see the result showing error.

1.39s$ groovy AddTests.groovy
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
.E
Time: 0.052
There was 1 error:
1) testAdditions(AddTests)groovy.lang.MissingPropertyException: No such property: c for class: Add
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at AddTests.testAdditions(AddTests.groovy:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1443)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeStaticMethod(InvokerHelper.java:945)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeStaticMethod(InvokerHelper.java:81)
	at groovy.lang.GroovyShell.runJUnit3Test(GroovyShell.java:375)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:295)
	at groovy.lang.GroovyShell.run(GroovyShell.java:524)
	at groovy.lang.GroovyShell.run(GroovyShell.java:513)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
FAILURES!!!
Tests run: 1,  Failures: 0,  Errors: 1


Compare Add.java code to write exactly.

```
import java.util.Scanner;
class Add
{
public static void main(String[] arg)
{
int a,b,c;
Scanner sc=new Scanner(System.in);
System.out.println("Enter first number");
a=sc.nextInt();
System.out.println("Enter second number");
b=sc.nextInt();
c=addition(a,b);
System.out.println(" Addition of two numbers is : "+c);
}
static int addition(int x,int y)
{
	return x+y;
}
}
```
