### ISSUE TITLE
Create Fail test for Java class using groovy

### ISSUE THREAD

**Issue by hemanth22** [hemanth22/GroovyLearning#3]
Create a fail test using groovy for java.

**Comment by hemanth22** [comment]
Updated test case in project, let's see the result.

**Comment by hemanth22** [comment]
Yes failure test case successful.

Result:

```
 groovy AddTests.groovy
Picked up _JAVA_OPTIONS: -Xmx2048m -Xms512m
.E
Time: 0.07
There was 1 error:
1) testAdditions(AddTests)Assertion failed:
assert 31 ==  account.addition(20,10)
          |   |       |
          |   |       30
          |   Add@363ee3a2
          false
	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:402)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
	at AddTests.testAdditions(AddTests.groovy:7)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeStaticMethod(MetaClassImpl.java:1443)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeStaticMethod(InvokerHelper.java:945)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeStaticMethod(InvokerHelper.java:81)
	at groovy.lang.GroovyShell.runJUnit3Test(GroovyShell.java:375)
	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:295)
	at groovy.lang.GroovyShell.run(GroovyShell.java:524)
	at groovy.lang.GroovyShell.run(GroovyShell.java:513)
	at groovy.ui.GroovyMain.processOnce(GroovyMain.java:652)
	at groovy.ui.GroovyMain.run(GroovyMain.java:384)
	at groovy.ui.GroovyMain.process(GroovyMain.java:370)
	at groovy.ui.GroovyMain.processArgs(GroovyMain.java:129)
	at groovy.ui.GroovyMain.main(GroovyMain.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.codehaus.groovy.tools.GroovyStarter.rootLoader(GroovyStarter.java:109)
	at org.codehaus.groovy.tools.GroovyStarter.main(GroovyStarter.java:131)
FAILURES!!!
Tests run: 1,  Failures: 0,  Errors: 1
```

**Comment by hemanth22** [comment]
Fail test success : https://travis-ci.org/hemanth22/GroovyLearning/builds/427006169

**Comment by hemanth22** [comment]
Hence closing the ticket :1st_place_medal:
